#!/usr/bin/env bash
# Script that displays a list of currently running processes, showing all
# processes, for all users, including those which might not have a TTY,
# displayed in a user-oriented format, and showing process hierarchy.
ps axuf
