#!/bin/bash
# Script that displays the content of the file /etc/passwd, displaying only
# username, user id, and home directory path for the user, using a while.
while read -r; do cut -d: -f1,3,6; done < /etc/passwd
