#!/bin/bash
# Script that displays the content of the file /etc/passwd, using the while
# loop + IFS.

#FORMAT: The user USERNAME is part of the GROUP_ID gang, lives in HOME_DIRECTORY and rides COMMAND/SHELL. USER ID's place is protected by the passcode PASSWORD, more info about the user here: USER ID INFO

while read -r -d: "USERNAME" "PASSWORD" "ID" "GROUP_ID" "INFO" "HOME_DIRECTORY" "COMMAND_SHELL"
do 
	printf "The user %s is part of the %s gang, lives in %s and rides %s. %s's place is protected by the passcode %s, more info about the user here: %s %s\n" "$USERNAME" "$GROUP_ID" "$HOME_DIRECTORY" "$COMMAND_SHELL" "$ID" "$PASSWORD" "$ID" "$INFO"
done < /etc/passwd
