#!/bin/bash
# Script that loops from 1 to 10 and displays "bad luck" "good luck" and
# "Best School" for the 4th, 8th, and other iterations, respectively.

i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"	
	else
		echo "Best School"
	fi

	((i++))
done
