#!/usr/bin/env bash
# Script that displays the content of the current directory in a list format
# where only the part of the name after the first dash is displayed.
for file in *
do
	echo "$file" | cut -d- -f2
done
