#!/bin/bash
# Script that prints information about the "school" file.

FILE="school"

#Test for whether file exists
if [ -e $FILE ]
then
	echo "school file exists"

	#Test for empty file
	if [ -s $FILE ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	#Test for regular file
	if [ -f $FILE ]
	then
		echo "school file is a regular file"
	fi
else
	echo "school file does not exist"
fi
